// <auto-generated />
using LocalBusiness.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LocalBusiness.Migrations
{
    [DbContext(typeof(LocalBusinessContext))]
    [Migration("20220819212242_BusinessV1")]
    partial class BusinessV1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("LocalBusiness.Models.Business", b =>
                {
                    b.Property<int>("BusinessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("BusinessId");

                    b.ToTable("Businesses");

                    b.HasData(
                        new
                        {
                            BusinessId = 1,
                            Address = "113 SE 28th Ave, Portland, OR 97214",
                            Description = "Fried Chicken Food Cart devoted to Korean and American Southern Flavors",
                            Genre = "Korean",
                            Name = "FOMO Chicken",
                            Price = 2,
                            Type = "Food Cart"
                        },
                        new
                        {
                            BusinessId = 2,
                            Address = "2046 NE Martin Luther King Jr Blvd, Portland, OR 97212",
                            Description = "A LGBTQ owned plant store specializing in rare plants.",
                            Genre = "Plant Nursery",
                            Name = "Arium Botanicals",
                            Price = 3,
                            Type = "Shop"
                        },
                        new
                        {
                            BusinessId = 3,
                            Address = "2137 E Burnside St, Portland, OR 97214",
                            Description = "A compact family owned mexican restaurant.",
                            Genre = "Mexican",
                            Name = "Ole Ole",
                            Price = 1,
                            Type = "Restaurant"
                        },
                        new
                        {
                            BusinessId = 4,
                            Address = "2031 NE Martin Luther King Jr Blvd, Portland, OR 97212",
                            Description = "Coffee shop serving fair trade locally roasted coffee beans.",
                            Genre = "Cafe",
                            Name = "Tinys Coffee",
                            Price = 1,
                            Type = "Coffee Shop"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
